# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'licensedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LicenseDialog(object):
    def setupUi(self, LicenseDialog):
        LicenseDialog.setObjectName("LicenseDialog")
        LicenseDialog.resize(673, 301)
        self.buttonBox = QtWidgets.QDialogButtonBox(LicenseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.emailentry = QtWidgets.QLineEdit(LicenseDialog)
        self.emailentry.setGeometry(QtCore.QRect(130, 10, 531, 25))
        self.emailentry.setObjectName("emailentry")
        self.EMail_label = QtWidgets.QLabel(LicenseDialog)
        self.EMail_label.setGeometry(QtCore.QRect(20, 10, 111, 17))
        self.EMail_label.setObjectName("EMail_label")
        self.registrationentry = QtWidgets.QLineEdit(LicenseDialog)
        self.registrationentry.setGeometry(QtCore.QRect(130, 40, 531, 25))
        self.registrationentry.setObjectName("registrationentry")
        self.Tegistration_label = QtWidgets.QLabel(LicenseDialog)
        self.Tegistration_label.setGeometry(QtCore.QRect(20, 40, 111, 17))
        self.Tegistration_label.setObjectName("Tegistration_label")

        self.retranslateUi(LicenseDialog)
        self.buttonBox.accepted.connect(LicenseDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LicenseDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LicenseDialog)

    def retranslateUi(self, LicenseDialog):
        _translate = QtCore.QCoreApplication.translate
        LicenseDialog.setWindowTitle(_translate("LicenseDialog", "Dialog"))
        self.EMail_label.setText(_translate("LicenseDialog", "EMail Address:"))
        self.Tegistration_label.setText(_translate("LicenseDialog", "Registration:"))
