# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lp2ctrlui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 798)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("LooperlativeIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 300, 771, 411))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 720, 631, 17))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuMIDI_IN_device = QtWidgets.QMenu(self.menu_File)
        self.menuMIDI_IN_device.setObjectName("menuMIDI_IN_device")
        self.menuMIDI_OUT_device = QtWidgets.QMenu(self.menu_File)
        self.menuMIDI_OUT_device.setObjectName("menuMIDI_OUT_device")
        self.menu_Debug = QtWidgets.QMenu(self.menubar)
        self.menu_Debug.setObjectName("menu_Debug")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Upgrade = QtWidgets.QAction(MainWindow)
        self.action_Upgrade.setObjectName("action_Upgrade")
        self.action_Status = QtWidgets.QAction(MainWindow)
        self.action_Status.setObjectName("action_Status")
        self.action_MIDI_Status = QtWidgets.QAction(MainWindow)
        self.action_MIDI_Status.setObjectName("action_MIDI_Status")
        self.actionRe_boot = QtWidgets.QAction(MainWindow)
        self.actionRe_boot.setObjectName("actionRe_boot")
        self.actionAvailable_Devices = QtWidgets.QAction(MainWindow)
        self.actionAvailable_Devices.setEnabled(False)
        self.actionAvailable_Devices.setObjectName("actionAvailable_Devices")
        self.actionindeviceexample = QtWidgets.QAction(MainWindow)
        self.actionindeviceexample.setCheckable(True)
        self.actionindeviceexample.setObjectName("actionindeviceexample")
        self.actionAvailable_Devices_2 = QtWidgets.QAction(MainWindow)
        self.actionAvailable_Devices_2.setEnabled(False)
        self.actionAvailable_Devices_2.setObjectName("actionAvailable_Devices_2")
        self.actionoutdeviceexample = QtWidgets.QAction(MainWindow)
        self.actionoutdeviceexample.setCheckable(True)
        self.actionoutdeviceexample.setObjectName("actionoutdeviceexample")
        self.menuMIDI_IN_device.addAction(self.actionAvailable_Devices)
        self.menuMIDI_IN_device.addSeparator()
        self.menuMIDI_OUT_device.addAction(self.actionAvailable_Devices_2)
        self.menuMIDI_OUT_device.addSeparator()
        self.menu_File.addAction(self.action_Upgrade)
        self.menu_File.addAction(self.menuMIDI_IN_device.menuAction())
        self.menu_File.addAction(self.menuMIDI_OUT_device.menuAction())
        self.menu_Debug.addAction(self.action_Status)
        self.menu_Debug.addAction(self.action_MIDI_Status)
        self.menu_Debug.addAction(self.actionRe_boot)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Debug.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Looperlative MIDI Controller"))
        self.label.setText(_translate("MainWindow", "Pan"))
        self.label_3.setText(_translate("MainWindow", "Feedback"))
        self.label_2.setText(_translate("MainWindow", "Volume"))
        self.label_6.setText(_translate("MainWindow", "Length"))
        self.label_7.setText(_translate("MainWindow", "Position"))
        self.label_4.setText(_translate("MainWindow", "Status"))
        self.label_5.setText(_translate("MainWindow", "Copyright 2021 Looperlative Audio Products, LLC"))
        self.menu_File.setTitle(_translate("MainWindow", "File"))
        self.menuMIDI_IN_device.setTitle(_translate("MainWindow", "MIDI IN device"))
        self.menuMIDI_OUT_device.setTitle(_translate("MainWindow", "MIDI OUT device"))
        self.menu_Debug.setTitle(_translate("MainWindow", "&Debug"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Upgrade.setText(_translate("MainWindow", "&Upgrade"))
        self.action_Status.setText(_translate("MainWindow", "&Status"))
        self.action_MIDI_Status.setText(_translate("MainWindow", "&MIDI Status"))
        self.actionRe_boot.setText(_translate("MainWindow", "Re&boot"))
        self.actionAvailable_Devices.setText(_translate("MainWindow", "Available Devices"))
        self.actionindeviceexample.setText(_translate("MainWindow", "indeviceexample"))
        self.actionAvailable_Devices_2.setText(_translate("MainWindow", "Available Devices"))
        self.actionoutdeviceexample.setText(_translate("MainWindow", "outdeviceexample"))

